### PR TITLE
Add Athena Space Tech Server

### PR DESCRIPTION
**Pull request by Faucon-Noir**

### CODE REVIEW

**Comment by DasSkelett** [comment]
Hey, your server has a password set. Is it a private one, or open for everyone?
If so, please either unset the password or set a website/Discord URL so interested players can contact and join you.

**Comment by Faucon-Noir** [comment]
> Hey, your server has a password set. Is it a private one, or open for everyone? If so, please either unset the password or set a website/Discord URL so interested players can contact and join you.

It's a private one. I'm still learning about LMP, and I'd like to test the master server connection settings and see what we can do to optimize the server while allowing mods. It is not meant to stay online more than 48 hours. A dozen people are helping me to set up a more open server in the long run.

Sorry for my potential english mistakes, I haven't practiced for almost 3 years

**Comment by DasSkelett** [comment]
In this case it doesn't fit as a dedicated server. Note that your server doesn't need to be declared as dedicated in order to be registered with the master servers, every server can do it (and does so by default).
The "dedicated" is more like a badge advertising a server as open for everyone and online 24/7, and allows you to make it appear in custom colours in the server browser.

Your english is pretty good!

**Comment by Faucon-Noir** [comment]
Ok thanks ^^
In this case I will stay on my ip and ports

Thanks for the quick response ^^

**Pull request closed without merging**
