### PR TITLE
Add dedicated server

### PR DESCRIPTION
**Pull request by mlltAero**
Add Ghost Server to dedicated server list.

### CODE REVIEW

**Comment by DasSkelett** [comment]
`ksp.descaltr.com` doesn't seem to be set up correctly, it doesn't return any A records.

**Comment by DasSkelett** [comment]
Obligatory question for dedicated servers: have you read through https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Dedicated-server and are you planning to keep it running 24/7 for a long time?

**Comment by mlltAero** [comment]
Right. Just realized that my A record is set up incorrectly.

**Comment by mlltAero** [comment]
> Obligatory question for dedicated servers: have you read through https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Dedicated-server and are you planning to keep it running 24/7 for a long time?

Yes, I am planning to run it 24/7.

**Comment by DasSkelett** [comment]
Sorry for the delay. The domain is fixed now indeed.
The domain however points to the same IP address as the one you added in the second line. The same address twice is unnecessary, can you remove the second one?

**Pull request closed without merging**
